let adminSession=JSON.parse(localStorage.getItem("ff_admin")||"null");
function adminLogin(){
 screen.innerHTML=`<div class="auth"><div class="authbox adminBox"><div class="adminLogo">FF HUB <span>ADMIN</span></div><h2>Admin Login</h2><input class="input" id="ae" placeholder="Admin Email"><input class="input" id="ap" type="password" placeholder="Admin Password"><button class="join" onclick="doAdminLogin()">LOGIN TO ADMIN PANEL</button><p><button class="link" onclick="auth()">← User Login</button></p></div></div>`;
}
async function doAdminLogin(){
 let r=await api("/api/admin/login","POST",{email:ae.value,password:ap.value});
 if(r.error)return toast(r.error);
 adminSession=r;localStorage.setItem("ff_admin",JSON.stringify(r));adminHome();
}
async function adminHome(){
 screen.innerHTML=`<div class="adminPage"><div class="adminTop"><div><span class="tag">CONTROL CENTER</span><h2>Admin Dashboard</h2></div><button class="secondary" onclick="adminLogout()">Logout</button></div><div class="adminStats"><div><b id="au">—</b><small>Users</small></div><div><b id="am">—</b><small>Matches</small></div><div><b id="aw">—</b><small>Withdrawals</small></div></div><div class="adminGrid"><button onclick="adminMatches()">🏆 Matches</button><button onclick="adminCreate()">➕ Create Match</button><button onclick="adminUsers()">👥 Users</button><button onclick="adminWithdrawals()">💸 Withdrawals</button><button onclick="adminNotify()">🔔 Notification</button><button onclick="adminSupport()">💬 Support</button></div></div>`;
 let [u,m,w]=await Promise.all([api("/api/admin/users"),api("/api/admin/matches"),api("/api/admin/withdrawals")]);$("#au").textContent=u.length;$("#am").textContent=m.length;$("#aw").textContent=w.filter(x=>x.status==="PENDING").length;
}
function adminLogout(){localStorage.removeItem("ff_admin");adminSession=null;auth()}
async function adminMatches(){let a=await api("/api/admin/matches");screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>Manage Matches</h2><button class="secondary" onclick="adminHome()">Dashboard</button></div>${a.map(m=>`<div class="adminCard"><b>${esc(m.name||"Match")}</b><small>${esc(m.map||"")} • ${esc(m.mode||"")} • ${m.joinedPlayers||0}/${m.maxPlayers||50}</small><div class="adminActions"><button onclick="adminRoom('${m.id}')">🔑 Room</button><button onclick="adminResult('${m.id}')">🏅 Result</button><button onclick="adminEdit('${m.id}')">✏️ Edit</button><button onclick="adminDelete('${m.id}')">🗑️ Delete</button></div></div>`).join("")||"<div class='row'>No matches.</div>"}</div>`}
async function adminCreate(existing){
 let m=existing||{};screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>${existing?"Edit":"Create"} Match</h2><button class="secondary" onclick="adminHome()">Back</button></div><input class="input" id="mn" placeholder="Match Name" value="${esc(m.name||"")}"><label class="upload">🖼️ Match Image <input type="file" id="mi" accept="image/*" onchange="previewImage(event)"></label><img id="preview" class="matchPreview" ${m.imageUrl?`src="${esc(m.imageUrl)}"`:"style='display:none'"}><input class="input" id="ms" type="datetime-local" value="${m.startTime?new Date(m.startTime).toISOString().slice(0,16):""}"><div class="two"><input class="input" id="mp" type="number" placeholder="Prize Pool ₹" value="${m.prizePool||""}"><input class="input" id="mk" type="number" placeholder="Per Kill ₹" value="${m.perKill||""}"></div><div class="two"><select class="input" id="mt"><option>Solo</option><option>Duo</option><option>Squad</option></select><select class="input" id="mm"><option>Bermuda</option><option>Purgatory</option><option>Kalahari</option><option>Alpine</option></select></div><div class="two"><input class="input" id="mx" type="number" value="${m.maxPlayers||50}" placeholder="Max Players"><input class="input" id="mef" type="number" value="${m.entryFee||0}" placeholder="Entry Fee ₹"></div><button class="join" onclick="saveMatch('${m.id||""}')">SAVE MATCH</button></div>`;
 if(m.mode)mt.value=m.mode;if(m.map)mm.value=m.map;
}
function previewImage(e){let f=e.target.files[0],img=$("#preview");if(f){img.src=URL.createObjectURL(f);img.style.display="block"}}
async function imageData(){let f=$("#mi")?.files?.[0];if(!f)return "";if(f.size>1200000){toast("Image should be under 1.2MB");return ""}return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
async function saveMatch(id){let imageUrl=await imageData();let b={name:mn.value,startTime:ms.value?new Date(ms.value).getTime():0,prizePool:Number(mp.value||0),perKill:Number(mk.value||0),mode:mt.value,map:mm.value,maxPlayers:Number(mx.value||50),entryFee:Number(mef.value||0),status:"UPCOMING"};if(imageUrl)b.imageUrl=imageUrl;let r=id?await api("/api/admin/matches/"+id,"POST",b):await api("/api/matches","POST",b);if(r.error)return toast(r.error);toast("Match saved");adminMatches()}
async function adminEdit(id){let a=await api("/api/admin/matches");adminCreate(a.find(x=>x.id===id))}
async function adminDelete(id){if(!confirm("Delete this match?"))return;let r=await api("/api/admin/matches/"+id,"DELETE");toast(r.error||"Deleted");adminMatches()}
async function adminRoom(id){let rid=prompt("Room ID"),pw=prompt("Room Password");if(rid===null)return;let r=await api("/api/matches/"+id+"/room","POST",{roomId:rid,roomPassword:pw||""});toast(r.error||"Room updated")}
async function adminResult(id){let raw=prompt('Result JSON, example: [{"gameName":"Player1","kills":5,"prize":200}]');if(!raw)return;try{let result=JSON.parse(raw);let r=await api("/api/matches/"+id+"/result","POST",{result});toast(r.error||"Result posted")}catch(e){toast("Invalid JSON")}}
async function adminUsers(){let a=await api("/api/admin/users");screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>Users</h2><button class="secondary" onclick="adminHome()">Back</button></div>${a.map(u=>`<div class="adminCard"><b>${esc(u.name)}</b><small>${esc(u.email)} • Wallet ${money(u.wallet)}</small><button class="secondary" onclick="blockUser('${u.id}',${!u.blocked})">${u.blocked?"UNBLOCK":"BLOCK"}</button></div>`).join("")}</div>`}
async function blockUser(id,b){let r=await api("/api/admin/user/"+id+"/block","POST",{blocked:b});toast(r.error||"Updated");adminUsers()}
async function adminWithdrawals(){let a=await api("/api/admin/withdrawals");screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>Withdrawals</h2><button class="secondary" onclick="adminHome()">Back</button></div>${a.map(w=>`<div class="adminCard"><b>${money(w.amount)} • ${esc(w.upi)}</b><small>${esc(w.status)} • ${new Date(w.createdAt).toLocaleString()}</small>${w.status==="PENDING"?`<div class="adminActions"><button onclick="withdrawAction('${w.userId}','${w.id}','APPROVED')">Approve</button><button onclick="withdrawAction('${w.userId}','${w.id}','REJECTED')">Reject</button></div>`:""}</div>`).join("")||"<div class='row'>No withdrawals.</div>"}</div>`}
async function withdrawAction(uid,id,status){let r=await api("/api/admin/withdrawals/"+uid+"/"+id,"POST",{status});toast(r.error||status);adminWithdrawals()}
async function adminNotify(){screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>Send Notification</h2><button class="secondary" onclick="adminHome()">Back</button></div><input class="input" id="nt" placeholder="Title"><textarea class="input" id="nm" placeholder="Message" rows="5"></textarea><input class="input" id="nu" placeholder="User ID (blank = all users)"><button class="join" onclick="sendNotification()">SEND</button></div>`}
async function sendNotification(){let r=await api("/api/admin/notify","POST",{title:nt.value,message:nm.value,userId:nu.value});toast(r.error||"Notification sent")}
async function adminSupport(){screen.innerHTML=`<div class="section adminSection"><div class="adminTop"><h2>Contact Support</h2><button class="secondary" onclick="adminHome()">Back</button></div><input class="input" id="sw" placeholder="WhatsApp number"><input class="input" id="sm" placeholder="Support message"><button class="join" onclick="saveSupport()">SAVE SUPPORT</button></div>`}
async function saveSupport(){let r=await api("/api/admin/support","POST",{whatsapp:sw.value,message:sm.value});toast(r.error||"Support updated")}
if(adminSession && !me)adminHome();
