let me=JSON.parse(localStorage.getItem("ff_user")||"null"),matches=[];
const $=s=>document.querySelector(s), money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const api=(u,m="GET",b)=>fetch(u,{method:m,headers:{"Content-Type":"application/json"},body:m==="GET"?undefined:JSON.stringify(b)}).then(r=>r.json());
function toast(t){alert(t)}
function auth(){screen.innerHTML=`<div class="auth"><div class="authbox"><div class="authlogo">FF HUB</div><input class="input" id="e" placeholder="Email"><input class="input" id="p" type="password" placeholder="Password"><button class="join" onclick="login()">LOGIN</button><p style="text-align:center;color:#8895a5">New player? <button class="link" onclick="regform()">Create account</button></p><p style="text-align:center;margin-top:18px"><button class="adminLink" onclick="adminLogin()">⚙ Admin Panel Login</button></p></div></div>`}
function regform(){document.querySelector(".authbox").innerHTML=`<div class="authlogo">FF HUB</div><input class="input" id="n" placeholder="Name"><input class="input" id="g" placeholder="Game Name"><input class="input" id="e" placeholder="Email"><input class="input" id="m" placeholder="Mobile"><input class="input" id="p" type="password" placeholder="Password"><button class="join" onclick="register()">CREATE ACCOUNT</button><p style="text-align:center"><button class="link" onclick="auth()">Back to Login</button></p>`}
async function login(){let r=await api("/api/login","POST",{email:e.value,password:p.value});if(r.error)return toast(r.error);me=r.user;localStorage.setItem("ff_user",JSON.stringify(me));show("home")}
async function register(){let r=await api("/api/register","POST",{name:n.value,gameName:g.value,email:e.value,mobile:m.value,password:p.value});if(r.error)return toast(r.error);me=r.user;localStorage.setItem("ff_user",JSON.stringify(me));show("home")}
async function refresh(){if(!me)return;let u=await api("/api/user/"+me.id);if(!u.error){me=u;localStorage.setItem("ff_user",JSON.stringify(me));wallet.textContent=Number(me.wallet||0).toLocaleString("en-IN")}}
async function show(p){if(!me){auth();return}await refresh();if(p==="home")home();if(p==="matches")matchpage();if(p==="history")history();if(p==="profile")profile();if(p==="notifications")notify()}
async function home(){screen.innerHTML=`<div class="hero"><span class="tag">SEASON 01 • BATTLE ARENA</span><h1>PLAY. COMPETE.<br>WIN REWARDS.</h1><p>Join tournaments, enter custom rooms and track results.</p><button class="join" onclick="show('matches')">EXPLORE MATCHES →</button></div><div class="section"><h2>🔥 Featured Matches</h2><div id="list"></div></div>`;matches=await api("/api/matches");render(matches.slice(0,4))}
async function matchpage(){screen.innerHTML=`<div class="section"><span class="tag">TOURNAMENT ARENA</span><h2>All Matches</h2><div id="list"></div></div>`;matches=await api("/api/matches");render(matches)}
function render(a){let l=$("#list");l.innerHTML=a.length?a.map(m=>`<article class="match"><div class="banner"><b>${esc(m.name||"Tournament")}</b></div><div class="body"><div class="chips"><span class="chip">${esc(m.mode||"BR")}</span><span class="chip">${esc(m.map||"Bermuda")}</span><span class="chip">${m.status||"UPCOMING"}</span></div><div class="grid"><div class="stat"><small>ENTRY</small><b>${money(m.entryFee)}</b></div><div class="stat"><small>PRIZE</small><b>${money(m.prizePool)}</b></div><div class="stat"><small>PLAYERS</small><b>${m.joinedPlayers||0}/${m.maxPlayers||50}</b></div></div><div style="color:#19d6ff;font-size:11px;margin-top:10px">⏱ ${m.startTime?new Date(m.startTime).toLocaleString():"Time TBA"}</div><button class="join" onclick="join('${m.id}')">${m.status==="RESULT"?"VIEW RESULT":"JOIN MATCH"}</button></div></article>`).join(""):"<div class='row'>No matches available.</div>"}
async function join(id){
 let m=matches.find(x=>x.id===id); if(!m)return;
 if(m.status==="RESULT"){result(m);return}
 let slots=await api("/api/matches/"+id+"/slots");
 let max=Number(m.maxPlayers||50);
 let html=`<div class="modal"><div class="modalbox"><button class="close" onclick="closeModal()">×</button><div class="tag">JOIN TOURNAMENT</div><h2>${esc(m.name||"Match")}</h2><input class="input" id="jg" placeholder="Enter Game Name" value="${esc(me.gameName||"")}">${(String(m.mode||"").toLowerCase().includes("squad")||String(m.mode||"").toLowerCase().includes("duo"))?`<input class="input" id="jt" placeholder="Enter Team Name">`:""}<p class="muted">Select your slot</p><div class="slots">${Array.from({length:max},(_,i)=>{let n=i+1,used=!!slots[n];return `<button class="slot ${used?"used":""}" ${used?"disabled":""} onclick="selectSlot(${n},this)">${n}${used?" ✓":""}</button>`}).join("")}</div><div id="selectedSlot" class="selected">No slot selected</div><button class="join" onclick="confirmJoin('${id}')">CONFIRM JOIN • ${money(m.entryFee)}</button></div></div>`;
 document.body.insertAdjacentHTML("beforeend",html);
}
let chosenSlot=null;
function selectSlot(n,el){chosenSlot=n;document.querySelectorAll(".slot").forEach(x=>x.classList.remove("selectedSlot"));el.classList.add("selectedSlot");$("#selectedSlot").textContent="Selected Slot: "+n}
function closeModal(){document.querySelector(".modal")?.remove()}
async function confirmJoin(id){
 if(!chosenSlot)return toast("Please select a slot");
 let game=$("#jg").value.trim(), team=$("#jt")?.value.trim()||"";
 if(!game)return toast("Enter Game Name");
 let r=await api("/api/matches/"+id+"/join","POST",{userId:me.id,gameName:game,teamName:team,slot:chosenSlot});
 if(r.error)return toast(r.error);
 closeModal();chosenSlot=null;await refresh();toast("Match joined • Slot "+r.slot);
 await matchpage();
}

function result(m){screen.innerHTML=`<div class="section"><span class="tag">MATCH RESULT</span><h2>${esc(m.name)}</h2>${(m.result||[]).map((x,i)=>`<div class="result"><b>#${i+1} ${esc(x.gameName||x.name)}</b><br>Prize ${money(x.prize||0)} • Kills ${x.kills||0}</div>`).join("")||"<div class='row'>Result not published.</div>"}<button class="secondary" onclick="matchpage()">Back</button></div>`}
async function history(){let h=await api("/api/history/"+me.id);screen.innerHTML=`<div class="section"><span class="tag">MY ACTIVITY</span><h2>History</h2>${h.joins.map(x=>`<div class="row"><span>${esc(x.gameName)}<small>Joined</small></span><b>-${money(x.entryFee)}</b></div>`).join("")||"<div class='row'>No joined matches.</div>"}<h2>Wallet</h2>${h.payments.map(x=>`<div class="row"><span>Wallet top-up</span><b>+${money(x.amount)}</b></div>`).join("")}</div>`}
async function profile(){await refresh();screen.innerHTML=`<div class="profile"><div style="display:flex;gap:13px;align-items:center"><div class="avatar">${esc((me.name||"P")[0])}</div><div><h2 style="margin:0">${esc(me.name)}</h2><small style="color:#8995a5">${esc(me.gameName)}</small></div></div><div class="balance">${money(me.wallet)}</div><div class="actions"><button onclick="add()">+ Add Money</button><button onclick="withdraw()">Withdraw</button></div><p><button class="secondary" style="width:100%" onclick="notify()">🔔 Notifications</button></p><p><button class="secondary" style="width:100%" onclick="alert('Contact Support: configure your WhatsApp/contact in the Admin settings.')">💬 Contact Support</button></p><button class="secondary" style="width:100%" onclick="localStorage.clear();location.reload()">Logout</button></div>`}
async function add(){let a=prompt("Wallet amount ₹10+","100");if(!a)return;let o=await api("/api/create-order","POST",{amount:a,userId:me.id}),c=await api("/api/config");if(o.error)return toast(o.error);new Razorpay({key:c.razorpayKeyId,amount:o.amount,currency:"INR",name:"FF Tournament Hub",description:"Wallet Top-up",order_id:o.id,handler:()=>toast("Payment submitted; wallet credits after verified webhook."),theme:{color:"#a7f327"}}).open()}
async function withdraw(){let a=prompt("Amount ₹50+","50"),u=prompt("UPI ID");if(!a||!u)return;let r=await api("/api/withdraw","POST",{userId:me.id,amount:a,upi:u});toast(r.error||"Withdrawal request submitted")}
async function notify(){let n=await api("/api/notifications/"+me.id);screen.innerHTML=`<div class="section"><span class="tag">UPDATES</span><h2>Notifications</h2>${n.map(x=>`<div class="notice"><b>${esc(x.title)}</b><p>${esc(x.message)}</p><small>${new Date(x.createdAt).toLocaleString()}</small></div>`).join("")||"<div class='row'>No notifications.</div>"}`}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
if(me)show("home");else auth();setInterval(refresh,10000);